#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define INPUT_FILENAME "input.bin" // binary filename which will be generated by this code

/*
 * Generates a binary input file for PIC interpolation.
 * File format:
 *   int NX, NY
 *   int NUM_Points
 *   int Maxiter
 *   For each iteration:
 *     NUM_Points pairs of (x, y) in [0, 1]
 */

void generate_input_file(int NX, int NY, int NUM_Points, int Maxiter) {

    // Open file in binary write mode
    FILE *fp = fopen(INPUT_FILENAME, "wb");
    if (fp == NULL) {
        perror("Error: Unable to create file input.bin\n");
        exit(EXIT_FAILURE);
    }

    // Write problem parameters 
    fwrite(&NX, sizeof(int), 1, fp);
    fwrite(&NY, sizeof(int), 1, fp);
    fwrite(&NUM_Points, sizeof(int), 1, fp);
    fwrite(&Maxiter, sizeof(int), 1, fp);

    // Seed random number generator 
    srand((unsigned int)time(NULL));

    // Write particle positions for each iteration 
    for (int iter = 0; iter < Maxiter; iter++) {
        for (int i = 0; i < NUM_Points; i++) {

            double x = (double)rand() / RAND_MAX; // Random x in [0,1]
            double y = (double)rand() / RAND_MAX; // Random x in [0,1]

            fwrite(&x, sizeof(double), 1, fp);
            fwrite(&y, sizeof(double), 1, fp);
        }
    }   

    fclose(fp);

    printf("Input file '%s' generated successfully.\n", INPUT_FILENAME);
}

int main() {

    int NX, NY;
    int NUM_Points;
    int Maxiter;

    // Read user input 
    printf("Enter grid dimensions (NX NY): ");
    scanf("%d %d", &NX, &NY);

    printf("Enter number of particles: ");
    scanf("%d", &NUM_Points);

    printf("Enter number of iterations: ");
    scanf("%d", &Maxiter);

    // Generate the binary input file
    generate_input_file(NX, NY, NUM_Points, Maxiter);

    return 0;
}